"""adicionado coluna telefone no usuario

Revision ID: 8f4995617a40
Revises: d78617e79fa8
Create Date: 2026-10-05 21:34:20.591391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f4995617a40'
down_revision: Union[str, Sequence[str], None] = 'd78617e79fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
