"""adicionado coluna plano no usuario

Revision ID: d78617e79fa8
Revises: abc730aff5fc
Create Date: 2026-10-05 21:33:51.719596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78617e79fa8'
down_revision: Union[str, Sequence[str], None] = 'abc730aff5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('plano', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'plano')
    # ### end Alembic commands ###
